apiVersion: mock.digi.dev/v1
kind: Appliance
metadata:
  name: {{ .Values.name }}
spec:
  control:
    power:
      intent: "on"
  meta:
    wattage: 24
    unit: watt
  egress:
    energy:
      flow: "watt | cut watt,event_ts"
